
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Branch
{

    public int BranchCode { get; set; }

    public int CityCityNumber { get; set; }

    public string BranchName { get; set; }

    public int BrandBrandCode { get; set; }

    public string Phone { get; set; }

    public string address { get; set; }

    public string googleMapURL { get; set; }



    public virtual Brand Brand { get; set; }

    public virtual City City { get; set; }

}

}
