
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Club_Required_Fields
{

    public int ClubClubId { get; set; }

    public int Required_FieldsFileldNo { get; set; }

    public Nullable<int> IsMandatory { get; set; }



    public virtual Club Club { get; set; }

    public virtual Required_Field Required_Fields { get; set; }

}

}
