
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Club_Customer
{

    public int ClubClubId { get; set; }

    public int CustomerIdNumber { get; set; }

    public Nullable<System.DateTime> RegistrationDate { get; set; }



    public virtual Club Club { get; set; }

    public virtual Customer Customer { get; set; }

}

}
