
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Children = new HashSet<Child>();

        this.Club_Customer = new HashSet<Club_Customer>();

        this.Customer_subCategory = new HashSet<Customer_subCategory>();

        this.CategoryChoices = new HashSet<CategoryChoice>();

    }


    public int IdNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> PhoneNo { get; set; }

    public string MainMail { get; set; }

    public int CityCityNumber { get; set; }

    public Nullable<int> NoOfKids { get; set; }

    public string gender { get; set; }

    public Nullable<System.DateTime> MarrigeDate { get; set; }

    public Nullable<System.DateTime> SignDate { get; set; }

    public string address { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Child> Children { get; set; }

    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Club_Customer> Club_Customer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Customer_subCategory> Customer_subCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CategoryChoice> CategoryChoices { get; set; }

}

}
