
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Customer_subCategory
{

    public int CustomerIdNumber { get; set; }

    public int subCategorySubNo { get; set; }

    public Nullable<int> checkedDate { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual subCategory subCategory { get; set; }

}

}
